force-app/main/default/objects/Shipment__c/Shipment__c.object-meta.xml
<CustomObject>
    <description>Object to hold all shipment details such as contents being shipped (cargo), who the sender and receiver are and where the shipment is going.</description>
    <label>Shipment</label>
    <nameField>
        <displayFormat>SH-{000000}</displayFormat>
        <label>Shipment Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Shipments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Shipment__c/fields/Estimated_Direct_Distance__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Direct_Distance__c</fullName>
    <description>Calculates the straight-line distance (see Step 3).</description>
    <formula>SQRT(
    (Destination_Planetary_System__r.X_Coordinate__c - Origin_Planetary_System__r.X_Coordinate__c) * (Destination_Planetary_System__r.X_Coordinate__c - Origin_Planetary_System__r.X_Coordinate__c) +

    (Destination_Planetary_System__r.Y_Coordinate__c - Origin_Planetary_System__r.Y_Coordinate__c) * (Destination_Planetary_System__r.Y_Coordinate__c - Origin_Planetary_System__r.Y_Coordinate__c) +

    (Destination_Planetary_System__r.Z_Coordinate__c - Origin_Planetary_System__r.Z_Coordinate__c) * (Destination_Planetary_System__r.Z_Coordinate__c - Origin_Planetary_System__r.Z_Coordinate__c)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Estimated Direct Distance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/Fuel_Cost__c.field-meta.xml
<CustomField>
    <fullName>Fuel_Cost__c</fullName>
    <description>The amount of fuel the shipment will cost.</description>
    <label>Fuel Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/Recipient__c.field-meta.xml
<CustomField>
    <fullName>Recipient__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Details of the party receiving the parcel.</description>
    <label>Recipient/Consignee</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Shipments</relationshipLabel>
    <relationshipName>Shipments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/Sender__c.field-meta.xml
<CustomField>
    <fullName>Sender__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Details of the Sender/Consignor of the parcel.</description>
    <label>Sender/Consignor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Shipments</relationshipLabel>
    <relationshipName>Shipments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/Shipping_Method__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Method__c</fullName>
    <description>Information on the type of space travel requested.</description>
    <label>Shipping Method</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Warp Drive</fullName>
            </value>
            <value>
                <fullName>Hyperspace</fullName>
            </value>
            <value>
                <fullName>Sub-light Cruise</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/Total_Delivery_Time__c.field-meta.xml
<CustomField>
    <fullName>Total_Delivery_Time__c</fullName>
    <description>The total number of time in days taken for the parcel to be delivered to the recipient. Calculated from Departure Date to Delivery Date.</description>
    <label>Total Delivery Time</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Shipment__c/fields/Total_Weight__c.field-meta.xml
<CustomField>
    <fullName>Total_Weight__c</fullName>
    <description>The total weight of all the cargo related to the Shipment.</description>
    <inlineHelpText>The total weight of all the cargo related to the Shipment.</inlineHelpText>
    <label>Total Cargo Weight</label>
    <summarizedField>Cargo__c.Weight__c</summarizedField>
    <summaryForeignKey>Cargo__c.Shipment__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/classes/FuelCostCalculator.cls
public class FuelCostCalculator {
    private static final Decimal FUEL_COST_PER_UNIT = 0.5;
    public List<ShipmentWrapper> shipmentList { get; set; }
    
    public FuelCostCalculator(ApexPages.StandardController stdController) {
        
        shipmentList = new List<ShipmentWrapper>();
        
        List<Shipment__c> shipments = [
            SELECT Name, Total_Weight__c, Shipping_Method__c,
            Total_Delivery_Time__c, Sender__r.Name, Recipient__r.Name, 
            Fuel_Cost__c, Estimated_Direct_Distance__c, Owner.Name FROM Shipment__c LIMIT 200
        ];
        
        for(Shipment__c sh: shipments) {
            ShipmentWrapper wrapper = new ShipmentWrapper();
            wrapper.shipment = sh;
            
            Decimal cost = 0;
            if (sh.Total_Weight__c != null && sh.Estimated_Direct_Distance__c != null) {
                cost = sh.Total_Weight__c * sh.Estimated_Direct_Distance__c * FUEL_COST_PER_UNIT;
             }
            
            wrapper.FuelCost = cost.setScale(2);
            
            shipmentList.add(wrapper);
        }
    }
    public class ShipmentWrapper {
            public Shipment__c shipment { get; set; }
            public Decimal FuelCost { get; set; }
        }
}